version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestSumiSharedProject
  gitServerName: sumitaAccountShared
  gitUrl: https://github.com/sumitaPriyadarshy
  gitUsername: sumitaPriyadarshy
  gitBranch: main
services:
- serviceName: project.testsumishared.integrations:testflow2
  packages:
  - name: TestSumiSharedProject
    version: "1.0"
- serviceName: project.testsumishared.integrations:testflow3
  packages:
  - name: TestSumiSharedProject
    version: "1.0"
- serviceName: project.testsumishared.integrations:testflow4
  packages:
  - name: TestSumiSharedProject
    version: "1.0"
